
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 25 19:10:09 CET 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OSB = 6;
  public static final int UMINUS = 14;
  public static final int CAST_FLOAT = 39;
  public static final int GTOREQ = 25;
  public static final int INT = 36;
  public static final int FOR = 40;
  public static final int MINUS = 11;
  public static final int CP = 3;
  public static final int NOT = 21;
  public static final int SEMICOLON = 8;
  public static final int AND = 19;
  public static final int LT = 22;
  public static final int IN = 44;
  public static final int OR = 20;
  public static final int COMMA = 9;
  public static final int OP = 2;
  public static final int INC = 17;
  public static final int DIV = 13;
  public static final int PLUS = 10;
  public static final int CB = 5;
  public static final int IF = 28;
  public static final int CAST_INT = 38;
  public static final int CSB = 7;
  public static final int EOF = 0;
  public static final int ASIG = 16;
  public static final int VAR_INT = 33;
  public static final int OB = 4;
  public static final int error = 1;
  public static final int MUL = 12;
  public static final int MOD = 15;
  public static final int EQ = 26;
  public static final int ELSE = 29;
  public static final int TO = 41;
  public static final int VAR_FLOAT = 34;
  public static final int WHILE = 30;
  public static final int FLOAT = 37;
  public static final int LTOREQ = 24;
  public static final int DOWNTO = 43;
  public static final int DEC = 18;
  public static final int GT = 23;
  public static final int VAR = 35;
  public static final int PRINT = 32;
  public static final int DO = 31;
  public static final int STEP = 42;
  public static final int NOTEQ = 27;
}

